"""
PolyAugur Signal Store - SQLite Persistence Layer
Stores all detected signals persistently.
Enables: deduplication, backtesting, performance tracking.
Author: Diego Ringleb | Phase 6 | 2026-02-28
"""

import sqlite3
import logging
from datetime import datetime, timezone, timedelta
from typing import Dict, List, Optional, Any
import os

logger = logging.getLogger(__name__)

DB_PATH = os.getenv("SIGNAL_DB_PATH", "data/signals.db")


class SignalStore:
    """
    SQLite-based signal persistence.

    Responsibilities:
    - Store every signal generated by the pipeline
    - Deduplicate: same market_id within DEDUP_WINDOW_HOURS not re-sent
    - Track Telegram delivery status
    - Provide query interface for analysis/backtesting
    """

    DEDUP_WINDOW_HOURS = 4  # Re-alert same market after 4h max

    def __init__(self, db_path: str = DB_PATH):
        self.db_path = db_path
        os.makedirs(os.path.dirname(self.db_path), exist_ok=True)
        self._init_db()
        logger.info(f"📦 SignalStore initialized → {self.db_path}")

    def _get_conn(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self.db_path)
        conn.row_factory = sqlite3.Row
        return conn

    def _init_db(self):
        """Create tables if not exist."""
        with self._get_conn() as conn:
            conn.execute("""
                CREATE TABLE IF NOT EXISTS signals (
                    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
                    market_id           TEXT NOT NULL,
                    question            TEXT,
                    trade               TEXT,
                    confidence          REAL,
                    anomaly_score       REAL,
                    anomaly_type        TEXT,
                    risk_level          TEXT,
                    yes_price           REAL,
                    volume_24hr         REAL,
                    spike_ratio         REAL,
                    days_to_close       INTEGER,
                    holding_hours       INTEGER,
                    position_size_pct   REAL,
                    reasoning           TEXT,
                    cycle               INTEGER,
                    detected_at         TEXT NOT NULL,
                    source              TEXT,
                    sent_telegram       INTEGER DEFAULT 0,
                    telegram_sent_at    TEXT
                )
            """)
            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_market_id
                ON signals (market_id, detected_at)
            """)
            conn.execute("""
                CREATE INDEX IF NOT EXISTS idx_detected_at
                ON signals (detected_at)
            """)
            conn.commit()

    def is_duplicate(self, market_id: str) -> bool:
        """
        Returns True if this market_id was already signaled
        within DEDUP_WINDOW_HOURS. Prevents spam on the same market.
        """
        cutoff = (
            datetime.now(timezone.utc) - timedelta(hours=self.DEDUP_WINDOW_HOURS)
        ).isoformat()

        with self._get_conn() as conn:
            row = conn.execute(
                """
                SELECT COUNT(*) as cnt FROM signals
                WHERE market_id = ?
                  AND detected_at >= ?
                """,
                (market_id, cutoff)
            ).fetchone()
        return row['cnt'] > 0

    def save(self, signal: Dict[str, Any]) -> int:
        """
        Persist a signal. Returns the new row ID.
        Caller should check is_duplicate() first.
        """
        # Extract spike_ratio from breakdown if present
        spike_ratio = (
            signal.get('spike_ratio') or
            signal.get('breakdown', {}).get('volume_spike', {}).get('spike_ratio', 1.0)
        )

        # days_to_close from end_date_iso
        days_to_close = None
        end_date = signal.get('end_date_iso')
        try:
            if end_date:
                closes = datetime.fromisoformat(end_date.replace('Z', '+00:00'))
                days_to_close = (closes - datetime.now(timezone.utc)).days
        except Exception:
            pass

        with self._get_conn() as conn:
            cursor = conn.execute(
                """
                INSERT INTO signals (
                    market_id, question, trade, confidence, anomaly_score,
                    anomaly_type, risk_level, yes_price, volume_24hr,
                    spike_ratio, days_to_close, holding_hours,
                    position_size_pct, reasoning, cycle,
                    detected_at, source, sent_telegram
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0)
                """,
                (
                    signal.get('market_id', ''),
                    signal.get('question', ''),
                    signal.get('recommended_trade', 'HOLD'),
                    signal.get('confidence_score', 0.0),
                    signal.get('score', signal.get('anomaly_score', 0.0)),
                    signal.get('anomaly_type', 'unknown'),
                    signal.get('risk_level', 'medium'),
                    signal.get('yes_price', 0.5),
                    signal.get('volume_24hr', 0.0),
                    spike_ratio,
                    days_to_close,
                    signal.get('holding_period_hours', 0),
                    signal.get('recommended_position_size_pct', 0.0),
                    signal.get('reasoning', ''),
                    signal.get('cycle', 0),
                    signal.get('detected_at', datetime.now(timezone.utc).isoformat()),
                    signal.get('source', 'unknown'),
                )
            )
            row_id = cursor.lastrowid
            conn.commit()

        logger.info(f"💾 Signal saved (id={row_id}): {signal.get('question', '')[:50]}")
        return row_id

    def mark_telegram_sent(self, row_id: int):
        """Mark a signal as sent via Telegram."""
        with self._get_conn() as conn:
            conn.execute(
                """
                UPDATE signals
                SET sent_telegram = 1,
                    telegram_sent_at = ?
                WHERE id = ?
                """,
                (datetime.now(timezone.utc).isoformat(), row_id)
            )
            conn.commit()

    def get_recent(self, hours: int = 24) -> List[Dict[str, Any]]:
        """Return all signals from the last N hours, newest first."""
        cutoff = (
            datetime.now(timezone.utc) - timedelta(hours=hours)
        ).isoformat()

        with self._get_conn() as conn:
            rows = conn.execute(
                """
                SELECT * FROM signals
                WHERE detected_at >= ?
                ORDER BY detected_at DESC
                """,
                (cutoff,)
            ).fetchall()

        return [dict(r) for r in rows]

    def get_stats(self) -> Dict[str, Any]:
        """Summary stats for logging/display."""
        with self._get_conn() as conn:
            total = conn.execute("SELECT COUNT(*) as n FROM signals").fetchone()['n']
            today_cutoff = (
                datetime.now(timezone.utc) - timedelta(hours=24)
            ).isoformat()
            today = conn.execute(
                "SELECT COUNT(*) as n FROM signals WHERE detected_at >= ?",
                (today_cutoff,)
            ).fetchone()['n']
            unsent = conn.execute(
                "SELECT COUNT(*) as n FROM signals WHERE sent_telegram = 0"
            ).fetchone()['n']

        return {
            'total_signals': total,
            'signals_24h': today,
            'telegram_unsent': unsent
        }


def main():
    """Standalone test."""
    import tempfile, os
    os.environ['SIGNAL_DB_PATH'] = '/tmp/test_signals.db'

    logging.basicConfig(level=logging.INFO)
    store = SignalStore('/tmp/test_signals.db')

    print("\n[Test 1] Save signal...")
    sig = {
        'market_id': 'test_market_001',
        'question': 'Will Trump nominate Michelle Bowman as Fed chair?',
        'recommended_trade': 'BUY_YES',
        'confidence_score': 0.87,
        'score': 0.58,
        'anomaly_type': 'volume_spike',
        'risk_level': 'medium',
        'yes_price': 0.73,
        'volume_24hr': 453000,
        'breakdown': {'volume_spike': {'spike_ratio': 9.0}},
        'days_to_close': 20,
        'holding_period_hours': 48,
        'recommended_position_size_pct': 0.10,
        'reasoning': '9x volume spike on Fed nomination 20d before close',
        'cycle': 1,
        'detected_at': datetime.now(timezone.utc).isoformat(),
        'source': 'mistral_batch'
    }
    row_id = store.save(sig)
    print(f"   ✅ Saved with id={row_id}")

    print("\n[Test 2] Deduplication check...")
    is_dup = store.is_duplicate('test_market_001')
    print(f"   ✅ is_duplicate={is_dup} (expected: True)")

    print("\n[Test 3] New market not duplicate...")
    is_dup2 = store.is_duplicate('different_market_999')
    print(f"   ✅ is_duplicate={is_dup2} (expected: False)")

    print("\n[Test 4] Mark telegram sent...")
    store.mark_telegram_sent(row_id)
    print(f"   ✅ Marked row {row_id} as sent")

    print("\n[Test 5] Stats...")
    stats = store.get_stats()
    print(f"   ✅ {stats}")

    print("\n[Test 6] Get recent...")
    recent = store.get_recent(hours=1)
    print(f"   ✅ {len(recent)} signals in last 1h")

    print("\n✅ SignalStore: ALL TESTS PASSED")


if __name__ == "__main__":
    main()
